# Generated by Django 5.2.13 on 2026-04-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_instructorprofile_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='certifications',
        ),
        migrations.AddField(
            model_name='user',
            name='is_instructor_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='qualification',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='interests',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor')], max_length=100),
        ),
    ]
