# Generated by Django 5.2.13 on 2026-04-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_managers_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='qualification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
