# Generated by Django 5.2.13 on 2026-04-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='file',
            field=models.FileField(upload_to='submissions/'),
        ),
    ]
