# Generated by Django 5.2.13 on 2026-04-24 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolled',
            old_name='COURSE',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='assignments',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='courses.subsection'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
