<<<<<<< HEAD
# Generated by Django 5.2.13 on 2026-04-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_enrolled_unique_user_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='description',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='topic',
        ),
    ]
=======
# Generated by Django 5.2.13 on 2026-04-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_enrolled_unique_user_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='description',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='topic',
        ),
    ]
>>>>>>> fb2d2e087fc74deb708398fda7513f10b81ef9c2
