<<<<<<< HEAD
# Generated by Django 5.2.13 on 2026-04-26 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_assignments_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='subsection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.subsection'),
        ),
    ]
=======
# Generated by Django 5.2.13 on 2026-04-26 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_assignments_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='subsection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.subsection'),
        ),
    ]
>>>>>>> fb2d2e087fc74deb708398fda7513f10b81ef9c2
