<<<<<<< HEAD
# Generated by Django 5.2.13 on 2026-04-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_assignments_subsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='file',
            field=models.FileField(upload_to='assignments/'),
        ),
    ]
=======
# Generated by Django 5.2.13 on 2026-04-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_assignments_subsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='file',
            field=models.FileField(upload_to='assignments/'),
        ),
    ]
>>>>>>> fb2d2e087fc74deb708398fda7513f10b81ef9c2
