<<<<<<< HEAD
# Generated by Django 5.2.13 on 2026-04-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_assignments_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='deadline',
            field=models.DateTimeField(default='2004-11-24'),
            preserve_default=False,
        ),
    ]
=======
# Generated by Django 5.2.13 on 2026-04-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_assignments_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='deadline',
            field=models.DateTimeField(default='2004-11-24'),
            preserve_default=False,
        ),
    ]
>>>>>>> fb2d2e087fc74deb708398fda7513f10b81ef9c2
