# Generated by Django 5.2.13 on 2026-04-26 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_assignments_deadline'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='user',
            field=models.ManyToManyField(through='submissions.Submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
