# Generated by Django 5.2.13 on 2026-04-26 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_assignments_user'),
        ('grading', '0001_initial'),
        ('submissions', '0002_alter_submissions_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='grades',
            field=models.ManyToManyField(related_name='assignments_grades', through='grading.Gradings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='user',
            field=models.ManyToManyField(related_name='submitted_assignments', through='submissions.Submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
