# Generated by Django 5.2.13 on 2026-04-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_assignments_grades_alter_assignments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
