# Generated by Django 5.2.13 on 2026-04-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_courses_is_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subsection',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='subsection',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subsection',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='subsection',
            constraint=models.UniqueConstraint(fields=('course', 'topic'), name='unique_topic_per_course'),
        ),
        migrations.AddConstraint(
            model_name='subsection',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_order_per_course'),
        ),
    ]
