# Generated by Django 5.2.13 on 2026-04-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_subsection_options_subsection_is_archived_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='file',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='user',
        ),
        migrations.AddField(
            model_name='assignments',
            name='assignment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignments',
            name='title',
            field=models.CharField(default='aom', max_length=255),
            preserve_default=False,
        ),
    ]
