# Generated by Django 5.2.13 on 2026-04-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradings',
            name='grades',
            field=models.IntegerField(default=0),
        ),
    ]
